name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.3.1

      - name: Install node packages
        run: yarn

      - name: Install additional Gatsby plugins
        run: yarn add gatsby-remark-reading-time gatsby-remark-katex --legacy-peer-deps || true
        
      # - name: Check lint
      #   run: yarn check:lint
        
      # - name: Check prettier
      #   run: yarn check:prettier
      
      - name: Build
        run: yarn build

      - name: Set git config
        run: |
          git config --global user.email "jaehun341012@gmail.com"
          git config --global user.name "jaehun"

      - name: Deploy To Github Pages
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: npm run deploy-gh
