name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.3.1

      - name: Install node packages
        run: yarn

      - name: Install gatsby-remark-reading-time
        run: npm install gatsby-remark-reading-time --legacy-peer-deps || true

      - name: Install gatsby-remark-katex
        run: yarn add gatsby-remark-katex || true
        
      # - name: Check lint
      #   run: yarn check:lint
        
      # - name: Check prettier
      #   run: yarn check:prettier
      
      - name: Build
        run: yarn build
